### ISSUE TITLE
Portability beyond x86_64

### ISSUE THREAD

**Issue by ghost** [wangbj/syscalls#10]
Currently, `syscalls` targets only `x86_64`. While this architecture is very common, other architectures (e.g. `i386`, `arm64`) may also be desirable targets. I believe enabling portability to other architectures would require the following main changes:

* Move `nr.rs` and `syscall.c` to a directory such as `arch/x86_64`.
* Modify `syscalls-gen` to write `nr.rs` to the appropriate directory for the architecture it is being run on.
* Add a wrapper module that reexports everything in the right `nr.rs` for the target.
* Build in the right `syscall.c` for the target.

I may get around to implementing this myself some day in the distant future, in which case I'll put in a PR.

**Comment by jasonwhite** [comment]
FYI, I've been working on this in the branch [jw/multi-arch](https://github.com/jasonwhite/syscalls/tree/jw/multi-arch). I have syscall tables generated for most of the architectures that Linux supports. The hold up now is with supporting the other architectures in [syscall.c](https://github.com/jasonwhite/syscalls/blob/master/src/syscall.c).

**Comment by jasonwhite** [comment]
This is largely done. Only `aarch64` remains at this point. Closing this in favor of #18.
