### ISSUE TITLE
How to get the raw syscall number from the enum?

### ISSUE THREAD

**Issue by ya0guang** [wangbj/syscalls#15]
Hi, I want to get the number and the name (in &str or String) from the syscall enum. 

I found `name` method is implemented for `SyscallNo` and each syscall has a number in the enum. Is there a way to get the number (e.g. in `i32`), from a `SyscallNo` enum?

Thank you!

**Comment by jasonwhite** [comment]
Since `SyscallNo` is `#[repr(i32)]`, you can just do `SyscallNo::SYS_read as i32`.

That's a good reminder to improve the docs!
