### ISSUE TITLE
`syscall0()` should maybe not be marked `readonly`

### ISSUE THREAD

**Issue by dvdhrm** [wangbj/syscalls#17]
The `syscall0()` helper currently uses a `readonly` annotation for the inline-asm. However, this does not necessarily apply to all system-calls, even though they might take no arguments. I would suggest dropping this annotation.

One particular example is the `RESTART_SYSCALL` system call, which takes no arguments and restarts a syscall that was interrupted. You are unlikely to invoke it directly, but you will see it in stack-frames during signal-handling. This system-call can definitely write to memory, but takes no arguments.

Also note that many linux system calls assume to work on the task_struct of the calling process. Things like `prctl()` allow saving custom user-space pointers per-task for various reasons (e.g., automatic lock-unfreezing on crash). Hence, there might be syscalls that take no arguments but inevitably end up writing to memory. Exit, for instance, writes to memory but could be argued does not apply here as it does not return, anyway.

I have not digged too far, yet, and this might be a rather theoretic issue. However, at the same time the speedup by using `readonly` seems negligible, given that the kernel writes the register-set to the stack, anyway. And for fast alternatives, the VDSO-entries are better.

Anyway, this is mostly meant as hint and suggestion to drop the `readonly` annotation. But feel free to close this, if you think it is worth it to keep.

**Comment by jasonwhite** [comment]
Great catch! I have no problem dropping the `readonly` annotation on `syscall0`. Any small performance boost isn't worth compromising correctness (if that is the case here).

I thought that `restart_syscall` is only called by the kernel, not user space. If that's true, then whatever code gen optimization that happens for `syscall0` shouldn't matter. I didn't think it was possible to observe `restart_syscall` except via `ptrace`. I had only anticipated this crate being used by user space, but I guess there is nothing stopping it from being used in the context of a kernel.

Just curious: Which `prctl` are you referring to? I thought that is what `set_robust_list` does. Regardless, like you said, it shouldn't matter when `exit` or `exit_group` are called. The process/thread is gone at that point and those syscalls would use `syscall1`, not `syscall0` anyway.

Happy to take a PR that removes it!

**Comment by dvdhrm** [comment]
> I thought that `restart_syscall` is only called by the kernel, not user space. If that's true, then whatever code gen optimization that happens for `syscall0` shouldn't matter. I didn't think it was possible to observe `restart_syscall` except via `ptrace`. I had only anticipated this crate being used by user space, but I guess there is nothing stopping it from being used in the context of a kernel.

Yes, you usually only see it when debugging. I think you do not even leave kernel-space when the RESTART_SYSCALL nr is used to replace the original.

> Just curious: Which `prctl` are you referring to? I thought that is what `set_robust_list` does. Regardless, like you said, it shouldn't matter when `exit` or `exit_group` are called. The process/thread is gone at that point and those syscalls would use `syscall1`, not `syscall0` anyway.

*sigh* Why do I strongly remember this being a prctl? You are of course correct, that's what I was referring to.

As I said, this was more like a `this looks fishy`. I have not actually found a real bug. But just imagine implementing the VDSO in rust, and one of the zero-arg calls like getpid() end up updating the VDSO. You should probably mark the VDSO as volatile, true. I don't know. Maybe I am overly pessimistic here.

If you feel like keeping it, let me know! Otherwise, I will gladly drop it, even if I cannot come up with a real bug. I am fine either way.

**Comment by jasonwhite** [comment]
Yep. I'm totally fine with getting dropping the `readonly` annotation. 👍

**Comment by dvdhrm** [comment]
Thanks! Now implemented in #19. I hope I clarified things in the commit-message suitably enough. I will close this issue as solved.
