### ISSUE TITLE
Support armv7 thumb-mode

### ISSUE THREAD

**Issue by androw** [wangbj/syscalls#36]
We're working on upgrading youki (which depends on syscalls) on alpine Linux. Everything went smooth except for armv7 arch + thumb-mode.

We're running into this error when building (for every occurence of this line in the file):
```
error: cannot use register `r7`: the frame pointer (r7) cannot be used as an operand for inline asm
  --> /home/buildozer/.cargo/registry/src/index.crates.io-1cd66030c949c28d/syscalls-0.6.9/src/syscall/arm.rs:29:9
   |
29 |         in("r7") n as usize,
   |         ^^^^^^^^^^^^^^^^^^^
```

It looks we can do something like this to add support:
https://github.com/bytecodealliance/rustix/commit/ebf562fb43a3860169aa69fd58112e5f28ff071e

**Comment by jasonwhite** [comment]
Should be fixed in 5590b21ae3643fa6e65402d6ed13a3d04ee71e13.

v0.6.10 has been published to include this change.
