### ISSUE TITLE
Don't panic on From i32

### ISSUE THREAD

**Issue by echelonh** [wangbj/syscalls#41]
Unless I misunderstood - `panic` seems rather extreme upon i32 parsing failure - why not return a result?
Or - add a `try_from` option?

**Comment by jasonwhite** [comment]
There's [`Sysno::new`](https://docs.rs/syscalls/latest/syscalls/enum.Sysno.html#method.new) which returns an `Option<Sysno>`. Does that solve your problem?

**Comment by echelonh** [comment]
Yeah, that'll probably do, thanks!
